### ISSUE TITLE
Evolution - CoffeeScript support

### ISSUE THREAD

**Issue by simonc** [staticmatic/staticmatic#1]
Hi,

It would be nice if staticmatic could support coffee script :)
This way, there would be a complete html/css/js stack.
Here is a link to it : http://github.com/jashkenas/coffee-script

I could help, if needed.

Thanks

**Comment by stevebartholomew** [comment]
Agreed - I'm currently looking into this.

Steve

**Comment by stevebartholomew** [comment]
Just spotted your pull request - thanks for that.  I'll try it out shortly.

Steve

**Comment by simonc** [comment]
Any news about this ?
