### ISSUE TITLE
scss files are not generated

### ISSUE THREAD

**Issue by bmihelac** [staticmatic/staticmatic#2]
In b3811554bb18846fc67022a5d28ace5b861a11ba,  css files are not generated for scss templates.

Without digging too much, I belive  || File.exists?(File.join(@src_dir, 'stylesheets', "#{name}.scss")) should be added

```
def template_exists?(name, dir = '')
  File.exists?(File.join(@src_dir, 'pages', dir, "#{name}.haml")) || File.exists?(File.join(@src_dir, 'stylesheets', "#{name}.sass"))
end
```

**Comment by staticmatic** [comment]
Oops - this is already in the alpha.4 gem release but somehow wasn't pushed to github.  All up now though.

Cheers,

Steve

**Comment by bmihelac** [comment]
I would say there is one more thing in build.rb it should generate from scss extensions too:

in build.rb, line 19

```
Dir["#{@src_dir}/stylesheets/**/*.{sass,scss}"].each do |path|
```
