### ISSUE TITLE
@layout persists across pages

### ISSUE THREAD

**Issue by jasonroelofs** [staticmatic/staticmatic#3]
We've got a staticmatic site that for most pages expects the default layout to be used (application.haml). We do have some pages that use custom layouts, and that works fine. The problem is that once I hit a page with an explicit @layout setting, that setting is then saved in staticmatic until the next @layout= call, leading to a broken website.

Top level pages should always revert to the default layout unless they explicitly say to use a specific layout.

**Comment by jasonroelofs** [comment]
Quick note: this functionality works fine with 0.10.6 and 0.10.7, but is broken in 0.10.8.

**Comment by stevebartholomew** [comment]
This has been fixed in the latest pre-release.
