### ISSUE TITLE
StaticMatic fails to set Compass configurations

### ISSUE THREAD

**Issue by imathis** [staticmatic/staticmatic#5]
I'm on staticmatic-0.11.0.alpha.5
my /config/site.rb file looks like this: http://github.com/imathis/staticmatic-starter/blob/master/config/site.rb
my compass config like this: http://github.com/imathis/staticmatic-starter/blob/master/config.rb

I'm noticing that when I run `compass compile` from terminal, I get compact css, yet when I run staticmatic build . I get the default css compression. Other things don't work either. If I set http_path to "/some/sub/directory/" in my compass config, my paths don't change in the output css when building with StaticMatic. When building with Compass my change correctly.

I added `puts "hello from compass config"` to my compass config.rb file to make sure it was being loaded at all. The message was output on the terminal with both `compass compile` and `staticmatic build .` so it seems that while StaticMatic is loading in the config, it's failing to set the Compass configuration properly.

I can help troubleshoot this if you need more info. Or I'd be glad to post a simple test case for you.

Cheers,
- Brandon

**Comment by stevebartholomew** [comment]
Hmm - thanks for reporting.  I'll check it out asap.  

Steve

**Comment by stevebartholomew** [comment]
This should be fixed with the latest pre release - and you don't need to manually include your compass config now: http://groups.google.com/group/staticmatic/browse_thread/thread/d076b6e85fa20d0d.

Steve

**Comment by imathis** [comment]
It's working as expected now. Thanks very much.
